name: "Kir-Dev blog"
url: http://kir-dev.sch.bme.hu
markdown: redcarpet
pygments: true
permalink: pretty
paginate: 6
timezone: Europe/Budapest
date_format: "%Y.%m.%d."

redcarpet:
    extensions:
        - autolink
        - strikethrough
        - no_intra_emphasis
